### ISSUE TITLE
Avoiding anti-aliasing when rendering bitmap fonts on a canvas

### ISSUE THREAD

**Issue by remolueoend** [tomchen/bdfparser-js#1]
Dear Tom
First of all, thank you very much for this library; it is already of great use to me.
I am reaching out to you because I am currently struggling with rendering a small (5x7) BDF font on a canvas: The font is hard to read due to anti-aliasing effects (see screenshot below). Do you have any experience with this, or do you know how to get a pixel-perfect bitmap rendering? I already tried to disable `canvasContext.imageSmoothingEnabled` without any luck.
![2022-02-28_19-19](https://user-images.githubusercontent.com/7881606/156036720-4b518426-701a-4980-a333-c173f6db868f.png)

Background: I want to render the website on a low-resolution LED matrix.

Thank you very much for any ideas.
Cheers and have a nice day, remolueoend

**Comment by remolueoend** [comment]
I have found a working solution in the meantime. Applying following CSS rules to the canvas solves this issue:
```css
canvas {
  image-rendering: -moz-crisp-edges;
  image-rendering: -webkit-crisp-edges;
  image-rendering: pixelated;
  image-rendering: crisp-edges;
}

```
